/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_FFmpeg_FFmpegNative */

#ifndef _Included_org_FFmpeg_FFmpegNative
#define _Included_org_FFmpeg_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_FFmpeg_FFmpegNative
 * Method:    Decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_FFmpeg_FFmpegNative_Decode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
